# Generated by Django 5.1.6 on 2025-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('inti', 'Informasi Inti'), ('tambahan', 'Informasi Tambahan')], max_length=20)),
            ],
        ),
    ]
