# Generated by Django 5.1.6 on 2025-04-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_news_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
