# Generated by Django 5.1.6 on 2025-05-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='path',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='report/'),
        ),
    ]
