# Generated by Django 5.1.6 on 2025-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_report_path_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
