# Generated by Django 5.1.6 on 2025-05-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_report_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='report/'),
        ),
    ]
