# Generated by Django 5.1.6 on 2025-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_report_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_surat', models.CharField(blank=True, max_length=20, null=True)),
                ('tanggal_surat', models.DateField()),
                ('nomor_surat', models.CharField(blank=True, max_length=20, null=True)),
                ('keperluan', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
