# Generated by Django 5.1.6 on 2025-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_report_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='kategori',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='report/'),
        ),
    ]
